version: '3.8'
services:
    main:
        container_name: Serve
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8000:8000
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3305
            DB_DATABASE: "${DB_DATABASE}"
            DB_USERNAME: "${DB_USERNAME}"
            DB_PASSWORD: "${DB_PASSWORD}"


    db:
        platform: linux/x86_64
        image: mysql:8.0
        container_name: Database
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - db:/var/lib/mysql
        ports:
            - 3305:3305

networks:
    laravel-exa:
        driver: bridge

volumes:
    db:
        driver: local
