version: '3.8'
services:
    main:
        container_name: Serve
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve'
        volumes:
            - .:/app
        ports:
            - 9000:9000
        environment:
            DB_CONNECTION: mysql
            DB_HOST: 2becj.h.filess.io
            DB_PORT: 3305
            DB_DATABASE: dbentrydata_purerubbed
            DB_USERNAME: dbentrydata_purerubbed
            DB_PASSWORD: 7a0928be2ea0b0699c9271dde8bf570a717c53b7

networks:
    laravel-exa:
        driver: bridge

volumes:
    db:
        driver: local
