# fly.toml app configuration file generated for entry-data-api on 2024-12-09T05:01:58+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'entry-data-api'
primary_region = 'sin'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_NAME="entry-data-api"
  APP_ENV ='production'
  APP_DEBUG="false"
  APP_URL="https://entry-data-api.fly.dev"

  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'

  DB_CONNECTION="mysql"
  BROADCAST_DRIVER="log"
  CACHE_DRIVER="file"
  QUEUE_CONNECTION="sync"
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
